app/blueprints/main.py
import os
import secrets

from PIL import Image
from flask import (
    request,
    render_template,
    url_for,
    flash,
    redirect,
    abort,
    Blueprint,
    current_app,
)
from flask_login import (
    login_user,
    logout_user,
    current_user,
    login_required,
)
from sqlalchemy.orm import joinedload

from ..forms import (
    LoginForm,
    RegistrationForm,
    UpdateAccountForm,
    PostForm,
)
from ..models import (
    User,
    Post,
)


bp = Blueprint("main", __name__)


@bp.route("/")
def home():
    template = "main/home.html"
    page = request.args.get("page", 1, type=int)
    posts = Post.query.paginate(page=page, per_page=5)
    return render_template(template, posts=posts)


@bp.route("/about")
def about():
    template = "main/about.html"
    return render_template(template, title="About")


@bp.route("/register", methods=["POST", "GET"])
def register():
    template = "main/register.html"
    form = RegistrationForm()
    context = {
        "title": "Register",
        "form": form,
    }

    if form.validate_on_submit():
        user = User(
            name=form.name.data,
            email=form.email.data,
        )
        user.password = form.password.data
        user.save()
        flash(
            f"Your account have been created! You are now able to login",
            "success",
        )
        return redirect(url_for("main.home"))

    return render_template(template, **context)


@bp.route("/login", methods=["POST", "GET"])
def login():
    template = "main/login.html"
    form = LoginForm()
    context = {
        "title": "Login",
        "form": form,
    }
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.verify_password(form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            flash(f"You have been logged in!", "success")
            return (
                redirect(next_page)
                if next_page
                else redirect(url_for("main.home"))
            )
        else:
            flash(
                f"Login Unsuccessful. Please check email or password", "danger"
            )
    return render_template(template, **context)


@bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(
        current_app.root_path, "static/main/profile_pics", picture_fn
    )

    output_size = (300, 300)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn


@bp.route("/account", methods=["GET", "POST"])
@login_required
def account():
    template = "main/account.html"
    form = UpdateAccountForm()
    context = {
        "title": "Account",
        "form": form,
    }
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.name = form.name.data
        current_user.email = form.email.data
        current_user.save()
        flash("You account have been updated", "success")
        return redirect(url_for("main.account"))

    elif request.method == "GET":
        form.name.data = current_user.name
        form.email.data = current_user.email

    context["image_file"] = url_for(
        "static", filename="main/profile_pics/" + current_user.image_file
    )
    return render_template(template, **context)


@bp.route("/post/new", methods=["GET", "POST"])
@login_required
def new_post():
    template = "main/create_post.html"
    form = PostForm()
    context = {
        "form": form,
        "title": "New Post",
        "legend": "New Post",
    }

    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            content=form.content.data,
            author=current_user,
        )
        post.save()
        flash("Your post has been created!", "success")
        return redirect(url_for("main.home"))
    return render_template(template, **context)


@bp.route("/post/<int:post_id>")
def post(post_id):
    template = "main/post.html"
    post = Post.query.options(joinedload("comments")).get_or_404(post_id)
    context = {
        "title": post.title,
        "post": post,
    }
    return render_template(template, **context)


@bp.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    template = "main/create_post.html"
    form = PostForm()
    context = {
        "title": "Update Post",
        "legend": "Update Post",
        "form": form,
    }

    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.save()
        flash("Your post has been update!", "success")
        return redirect(url_for("main.post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template(template, **context)


@bp.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    post.delete()
    flash("Your post has been deleted!", "success")
    return redirect(url_for("main.home"))


@bp.route("/post/user/<string:user>", methods=["GET"])
def post_by_user(user):
    pass

app/blueprints/oauth2.py
from flask import (
    Blueprint,
    request,
    redirect,
    url_for,
    current_app,
    redirect,
    flash,
)
from flask_login import login_user
from ..oauth2_client import (
    GoogleOAuth2Client,
    FacebookOAuth2Client,
)
from ..models import User


bp = Blueprint("oauth2", __name__)


@bp.route("/google")
def login_with_google():
    request_uri = GoogleOAuth2Client.get_grant_request_url(
        client_id=current_app.config["GOOGLE_CLIENT_ID"],
        redirect_uri=url_for("oauth2.google_callback", _external=True),
        scope=["openid", "email", "profile"],
    )
    return redirect(request_uri)


@bp.route("/facebook")
def login_with_facebook():
    request_uri = FacebookOAuth2Client.get_grant_request_url(
        client_id=current_app.config["FACEBOOK_CLIENT_ID"],
        redirect_uri=url_for("oauth2.facebook_callback", _external=True),
        scope=["email"],
    )
    return redirect(request_uri)


@bp.route("/callback/google")
def google_callback():
    code = request.args.get("code", type=str)
    userinfo = GoogleOAuth2Client.get_userinfo(
        client_id=current_app.config["GOOGLE_CLIENT_ID"],
        client_secret=current_app.config["GOOGLE_CLIENT_SECRET"],
        code=code,
        authorization_response=request.url,
    )
    email = userinfo.get("email")
    user = User.query.filter_by(email=email).first()
    if not user:
        flash("You need to register this email before login", "danger")
        return redirect(url_for("main.register"))

    login_user(user)
    flash(f"Login with {email}", "success")
    return redirect(url_for("main.home"))


@bp.route("/callback/facebook")
def facebook_callback():
    code = request.args.get("code", type=str)
    userinfo = FacebookOAuth2Client.get_userinfo(
        client_id=current_app.config["FACEBOOK_CLIENT_ID"],
        client_secret=current_app.config["FACEBOOK_CLIENT_SECRET"],
        code=code,
        authorization_response=request.url,
    )
    email = userinfo.get("email")
    user = User.query.filter_by(email=email).first()
    if not user:
        flash("You need to register this email before login", "danger")
        return redirect(url_for("main.register"))

    login_user(user)
    flash(f"Login with {email}", "success")
    return redirect(url_for("main.home"))

app/main.py
import os
import secrets

from PIL import Image
from flask import (
    request,
    render_template,
    url_for,
    flash,
    redirect,
    abort,
    Blueprint,
    current_app,
)
from flask_login import (
    login_user,
    logout_user,
    current_user,
    login_required,
)

from .forms import (
    LoginForm,
    RegistrationForm,
    UpdateAccountForm,
    PostForm,
)
from .models import (
    User,
    Post,
)


bp = Blueprint('main', __name__)


@bp.route('/')
def home():
    template = 'main/home.html'
    page = request.args.get('page', 1, type=int)
    posts = Post.query.paginate(page=page, per_page=5)
    return render_template(template, posts=posts)


@bp.route('/about')
def about():
    template = 'main/about.html'
    return render_template(template, title='About')


@bp.route('/register', methods=['POST', 'GET'])
def register():
    template = 'main/register.html'
    form = RegistrationForm()
    context = {
        'title': 'Register',
        'form': form,
    }

    if form.validate_on_submit():
        user = User(
            name=form.name.data,
            email=form.email.data,
        )
        user.password = form.password.data
        user.save()
        flash(f'Your account have been created! You are now able to login', 'success')
        return redirect(url_for('main.home'))

    return render_template(template, **context)


@bp.route('/login', methods=['POST', 'GET'])
def login():
    template = 'main/login.html'
    form = LoginForm()
    context = {
        'title': 'Login',
        'form': form,
    }
    if (form.validate_on_submit()):
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.verify_password(form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f'You have been logged in!', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'Login Unsuccessful. Please check email or password', 'danger')
    return render_template(template, **context)


@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/main/profile_pics', picture_fn)

    output_size = (300, 300)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn


@bp.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    template = 'main/account.html'
    form = UpdateAccountForm()
    context = {
        'title': 'Account',
        'form': form,
    }
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.name = form.name.data
        current_user.email = form.email.data
        current_user.save()
        flash('You account have been updated', 'success')
        return redirect(url_for('main.account'))

    elif request.method == 'GET':
        form.name.data = current_user.name
        form.email.data = current_user.email

    context['image_file'] = url_for('static', filename='main/profile_pics/'+current_user.image_file)
    return render_template(template, **context)


@bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    template = 'main/create_post.html'
    form = PostForm()
    context = {
        'form': form,
        'title': 'New Post',
        'legend': 'New Post',
    }

    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            content=form.content.data,
            author=current_user,
        )
        post.save()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template(template, **context)


@bp.route('/post/<int:post_id>')
def post(post_id):
    template = 'main/post.html'
    post = Post.query.get_or_404(post_id)
    context = {
        'title': post.title,
        'post': post,
    }
    return render_template(template, **context)


@bp.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    template = 'main/create_post.html'
    form = PostForm()
    context = {
        'title': 'Update Post',
        'legend': 'Update Post',
        'form': form,
    }

    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.save()
        flash('Your post has been update!', 'success')
        return redirect(url_for('main.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template(template, **context)


@bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    post.delete()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('home'))


@bp.route('/post/user/<string:user>', methods=['GET'])
def post_by_user(user):
    pass

app/templates/main/about.html
{% extends "main/layout.html" %}
{% block content %}
<h1>About page</h1>
{% endblock content %}

app/templates/main/account.html
{% extends "main/layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.name}}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}

                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

app/templates/main/home.html
{% extends "main/layout.html" %}
{% block content %}
    {% for post in posts.items  %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='main/profile_pics/'+post.author.image_file)  }}" alt=""/>
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ post.author.username  }}</a>
                    <small class="text-muted">{{ post.created_at.strftime('%Y-%m-%d')  }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('main.post', post_id=post.id)  }}">{{ post.title  }}</a></h2>
                <p class="article-content">{{ post.content  }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

app/templates/main/layout.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta name="viewport" content="width=device-width" />
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='main/main.css')  }}" type="text/css" media="screen" title="no title" charset="utf-8">

        {% if title %}
        <title>Flask Blog - {{ title  }}</title>
        {% else %}
        <title>Flask Blog</title>
        {% endif %}
    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="/">Flask Blog</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link" href="{{ url_for('main.home')  }}">Home</a>
                            <a class="nav-item nav-link" href="{{ url_for('main.about')  }}">About</a>
                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            {% if current_user.is_authenticated %}
                                <a class="nav-item nav-link" href="{{ url_for('main.new_post') }}">New Post</a>
                                <a class="nav-item nav-link" href="{{ url_for('main.account') }}">Account</a>
                                <a class="nav-item nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                            {% else %}
                                <a class="nav-item nav-link" href="{{ url_for('main.login')  }}">Login</a>
                                <a class="nav-item nav-link" href="{{ url_for('main.register')  }}">Register</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>

        <main role="main" class="container">
            <div class="row">
                <div class="col-md-8">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category  }}">
                                    {{ message  }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}
                </div>
                <div class="col-md-4">
                    <div class="content-section">
                        <h3>Our Sidebar</h3>
                        <p class='text-muted'>You can put any information here you'd like.
                            <ul class="list-group">
                                <li class="list-group-item list-group-item-light">Latest Posts</li>
                                <li class="list-group-item list-group-item-light">Announcements</li>
                                <li class="list-group-item list-group-item-light">Calendars</li>
                                <li class="list-group-item list-group-item-light">etc</li>
                            </ul>
                        </p>
                    </div>
                </div>
            </div>
        </main>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

app/templates/main/login.html
{% extends "main/layout.html" %}

{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {{ form.hidden_tag()  }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control  is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control ') }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control  is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class='form-control ') }}
                    {% endif %}
                </div>

                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>

                <small class="text-muted ml-2">
                    <a href="#">Forgot password</a>
                </small>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>

        <hr>

        <p class="text-center">or login with</p>
        <div class="oauth2-login mb-3">
          <a href="{{ url_for('oauth2.login_with_facebook') }}" class="btn btn-primary facebook"> Login with Facebook <i class="fab fa-facebook-f ml-2"></i> </a>
          <a href="{{ url_for('oauth2.login_with_google') }}" class="btn btn-primary google-plus"> Login with Google <i class="fab fa-google-plus-g ml-2"></i> </a>
        </div>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Need A Account? <a class="ml-2" href="{{ url_for('main.register') }}">Sign Up Now</a>
        </small>
    </div>

{% endblock content %}

app/templates/main/post.html
{% extends "main/layout.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='main/profile_pics/'+post.author.image_file)  }}" alt=""/>
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ post.author.name }}</a>
                <small class="text-muted">{{ post.created_at.strftime('%Y-%m-%d')  }}</small>
                {% if post.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('main.update_post', post_id=post.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}
            </div>
            <h2><a class="article-title" href="{{ url_for('main.post', post_id=post.id) }}">{{ post.title  }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>

    <div class="comment-list ml-3 border">
        {% for comment in post.comments %}
            <div class="media p-3">
                <img src="{{ url_for('static', filename='main/profile_pics/'+comment.user.image_file) }}" alt="{{ comment.user.name }}" class="mr-3 rounded-circle comment-img" >
                <div class="media-body">
                  <a href="#" style="font-size:15px;">{{ comment.user.name }}</a> <small style="font-size:11px;"><i>{{comment.created_at.strftime('%Y-%m-%d')}}</i></small>
                  <p>{{ comment.content }}</p>
                </div>
            </div>
        {% endfor %}
    </div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('main.delete_post', post_id=post.id)  }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete" />
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/main/register.html
{% extends "main/layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {{ form.hidden_tag()  }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}

                    {% if form.name.errors %}
                        {{ form.name(class="form-control  is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class='form-control ') }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control  is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control ') }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control  is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class='form-control ') }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control  is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class='form-control ') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have A Account? <a class="ml-2" href="{{ url_for('main.login') }}">Sign In</a>
        </small>
    </div>

{% endblock content %}